[ 2025-04-04 20:34:01,116 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-04-04 20:34:01,117 ] root - INFO - Getting the data from mongodb
[ 2025-04-04 20:34:01,117 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-04-04 20:34:01,118 ] root - INFO - Exporting data from mongodb
[ 2025-04-04 20:34:01,118 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-04-04 20:34:01,118 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-04-04 20:34:01,119 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-04-04 20:34:01,119 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-04-04 20:34:01,120 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-04-04 20:34:01,120 ] root - ERROR - Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\pipline\training_pipeline.py] at line number [59]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\omman\Desktop\Dot batch\MLOps Project\Vechicle_Incurrance_proj\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
